#!/usr/bin/env python
#
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
import sys
from pprint import pprint
import layint_api
from layint_api.rest import ApiException
from vyper import v
from li_utils.envtools import env_setup

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
parser.add_argument("--name", help="Name for policy")
args = parser.parse_args()

env_setup()

layint_api.configuration.api_key['Authorization'] = v.get("api_key")
policy_api = layint_api.PolicyApi()
policy_api.api_client.host = v.get("api_host")

policy = layint_api.Policy()
if args.name:
    policy.name = args.name
else:
    policy.name = "Prevent all network syscalls"

policy.description = "Deny all network syscalls"
policy.default_file_action = "allow"
policy.default_network_action = "allow"
policy.default_program_action = "allow"
policy.schema_version = "v1.0"
policy.suspend = False
policy.rules = []

network_syscalls = [ 
"accept",
"accept4",
"bind",
"connect",
"getpeername",
"getsockname",
"getsockopt",
"listen",
"recv",
"recvfrom",
"recvmmsg",
"recvmsg",
"send",
"sendmmsg",
"sendmsg",
"sendto",
"setsockopt",
"shutdown",
"socket",
"socketcall",
"socketpair" ]

for syscall in network_syscalls:
    rule = layint_api.PolicyRule()
    rule.name = "Deny " + syscall
    rule.action = "deny"
    rule.rule_type = "syscall"
    rule.syscall = "sys_" + syscall
    policy.rules.append(rule)

# Create new Policy definition
if args.verbose:
    print("Creating Policy %s on API host %s..." % (policy.name, v.get("api_host")))
try:
    api_response = policy_api.add_policy(policy=policy)
    policy.id = api_response.id
    if args.verbose:
        pprint(api_response)
except ApiException as e:
    print("Exception when calling PolicyApi->add_policy: %s\n" % e)
    sys.exit(1)

if args.verbose:
    print("Policy created, ID " + str(policy.id))
else:
    print(str(policy.id))
