#!/usr/bin/env python
#
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
import sys
from pprint import pprint
import layint_api
from layint_api.rest import ApiException
from vyper import v
from li_utils.envtools import env_setup

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
parser.add_argument("--src-port", help="Source port to match rule", default="-1")
parser.add_argument("--src-ip",   help="Source IP   to match rule", default="*")
parser.add_argument("--dst-port", help="Dest   port to match rule", default="-1")
parser.add_argument("--name", help="Name for policy")
args = parser.parse_args()

env_setup()

layint_api.configuration.api_key['Authorization'] = v.get("api_key")
policy_api = layint_api.PolicyApi()
policy_api.api_client.host = v.get("api_host")

policy = layint_api.Policy()
if args.name:
    policy.name = args.name
else:
    policy.name = "Prevent accept with sys_accept"
policy.description = "Blocks accepted connections by src IP,port, dest port"
policy.default_file_action = "allow"
policy.default_network_action = "allow"
policy.default_program_action = "allow"
policy.schema_version = "v1.0"
policy.suspend = False

policy.rules = []
ip_rule = layint_api.PolicyRule()
ip_rule.name = "Stop accept for matching connections"
ip_rule.rule_type = "syscall"
ip_rule.program = "*"
ip_rule.syscall = "sys_accept"
ip_rule.arg1 = args.src_port # src port. -1 is our "integer wildcard"
ip_rule.arg2 = args.src_ip   # src IP
# arg3 is not actually an accept syscall argument, but is used by LI to check the bind/dst port
ip_rule.arg3 = args.dst_port # dest/bind port
ip_rule.action = "deny"
policy.rules.append(ip_rule)

# Create new Policy definition
if args.verbose:
    print("Creating Policy %s on API host %s..." % (policy.name, v.get("api_host")))
try:
    api_response = policy_api.add_policy(policy=policy)
    policy.id = api_response.id
    if args.verbose:
        pprint(api_response)
except ApiException as e:
    print("Exception when calling PolicyApi->add_policy: %s\n" % e)
    sys.exit(1)

if args.verbose:
    print("Policy created, ID " + str(policy.id))
else:
    print(str(policy.id))
